"""prima struttura

Revision ID: 547cdec08604
Revises: 
Create Date: 2026-04-09 10:26:16.132638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547cdec08604'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('comune', sa.String(length=150), nullable=False),
    sa.Column('indirizzo', sa.String(length=255), nullable=False),
    sa.Column('tipologia_lavoro', sa.String(length=150), nullable=False),
    sa.Column('urgenza', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=False),
    sa.Column('budget', sa.String(length=100), nullable=False),
    sa.Column('stato', sa.String(length=50), nullable=False),
    sa.Column('note_interne', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chiave', sa.String(length=100), nullable=False),
    sa.Column('valore', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chiave')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cognome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('ruolo', sa.String(length=30), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titolo', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('luogo', sa.String(length=150), nullable=False),
    sa.Column('descrizione_breve', sa.Text(), nullable=False),
    sa.Column('descrizione_completa', sa.Text(), nullable=False),
    sa.Column('stato', sa.String(length=50), nullable=False),
    sa.Column('visibile_pubblico', sa.Boolean(), nullable=False),
    sa.Column('in_evidenza', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('quote_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_request_id', sa.Integer(), nullable=False),
    sa.Column('nome_file_originale', sa.String(length=255), nullable=False),
    sa.Column('nome_file_salvato', sa.String(length=255), nullable=False),
    sa.Column('percorso_file', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nome_pubblico', sa.String(length=150), nullable=False),
    sa.Column('ruolo_pubblico', sa.String(length=150), nullable=False),
    sa.Column('descrizione_breve', sa.Text(), nullable=False),
    sa.Column('anni_esperienza', sa.Integer(), nullable=False),
    sa.Column('competenze', sa.Text(), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=False),
    sa.Column('ordine_visualizzazione', sa.Integer(), nullable=False),
    sa.Column('visibile_pubblico', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('project_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_photos')
    op.drop_table('technicians')
    op.drop_table('quote_attachments')
    op.drop_table('projects')
    op.drop_table('users')
    op.drop_table('site_settings')
    op.drop_table('quote_requests')
    # ### end Alembic commands ###
